name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Set the correct Node version using nvm
      shell: bash -l {0} 
      run: nvm install
    - run: npm ci
    - run: npm run lint
    - run: npm test


 - name: Set up node using nvm
  # You may pin to the exact commit or the version.
  # uses: dcodeIO/setup-node-nvm@b6d6ed786666dee7d42186617cbb1394070de579
  uses: dcodeIO/setup-node-nvm@v5
  with:
    # The node.js version to use according to nvm. Uses the version specified in .nvmrc if omitted.
    node-version: # optional, default is 
    # The node.js mirror to use
    node-mirror: # optional, default is https://nodejs.org/dist/
          